### ISSUE TITLE
unable to remove retweets

### ISSUE THREAD

**Issue by tristan-k** [chrisenytc/rmt#3]
```
$ sudo rmt remove

              _____           _______
             |  __ \         |__   __|
             | |__) | _ __ ___  | |
             |  _  / | '_ ` _ \ | |
             | | \ \ | | | | | || |
             |_|  \_\|_| |_| |_||_|

  RmT: A CLI tool to remove all your tweets at once

  Repo => https://github.com/chrisenytc/rmt
  Powered by => Christopher EnyTC

[?] You really want to remove your last tweet? Yes

Removing  "RT @iNPUTmice: Your friends refuse to spend $2 on the best OpenSource #XMPP client for Android? RT to win 1/50 free promo codes for https:/…"
/usr/local/lib/node_modules/rmt/lib/rmt.js:328
                                    reject(new Error(err[0].message));
                                                           ^

TypeError: Cannot read property 'message' of undefined
    at /usr/local/lib/node_modules/rmt/lib/rmt.js:328:60
    at Request._callback (/usr/local/lib/node_modules/rmt/node_modules/twitter/lib/twitter.js:150:9)
    at Request.self.callback (/usr/local/lib/node_modules/rmt/node_modules/twitter/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/rmt/node_modules/twitter/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/rmt/node_modules/twitter/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by chrisenytc** [comment]
Thank for report this error @tristan-k. I will fix this week. 👍
